### ISSUE TITLE
Long vehicles (buses, trucks, etc) giving way when they have right-of-way

### ISSUE THREAD

**Issue by Drift91** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#199] opened 2018-07-18 01:48 UTC
So I have several intersections where a Congo-line of buses has accumulated despite the road the buses are coming from has right-of-way over the other directions of traffic. The other roads are all set to yield, yet they constantly flow through until the bus despawns and a shorter vehicle forces it's way though as it should. I've also noticed similar problems happening with cargo trucks in the roundabouts of my industrial district, where they'll momentarily clog up the whole roundabout to give-way to cars entering the roundabout. Fortunately in this case there's enough vehicles of similar length to alleviate the problem.

If you need my save I've posted it in #198

**Comment by VictorPhilipp** [comment] 2018-07-20 20:47
I think multiple things play a role here:
- Vehicles do not enter a junction when the lane right behind the junction is occupied. That's of course more likely to be noticable for long vehicles like busses or heavy trucks.
- If a vehicle on a give-way road decides to enter the junction vehicles even vehicles on a right-of-way road wait for the first vehicle to leave the junction.
- Determining whether two roads are positioned left/right/straight to each other is currently not working properly which causes the priority rules logic to fail: This affects junctions where segments are connected with relative angles of between 0° and 30°, or between 150° and 180°.

The last point will be fixed with the next update. Remaining points are working as intended.

**Closed** 2018-07-20 22:13 UTC
Labels: bug
