### ISSUE TITLE
Network Restrictions not working.

### ISSUE THREAD

**Issue by Swamp-Ig** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#17] opened 2016-09-08 04:19 UTC
Hi,

I'm unable to use network restrictions. The UI for it doesn't come up.

This happens if I load from a save, or into a new game, or whatever. The exception gets thrown from the same `HasJunctionRestrictions` function, but called from a few different places.

Here is the relevant log output:

```
NullReferenceException: Object reference not set to an instance of an object
  at TrafficManager.Manager.JunctionRestrictionsManager.HasJunctionRestrictions (UInt16 nodeId) [0x00000] in <filename unknown>:0 

  at TrafficManager.UI.SubTools.JunctionRestrictionsTool.RefreshCurrentRestrictedNodeIds () [0x00000] in <filename unknown>:0 

  at TrafficManager.UI.SubTools.JunctionRestrictionsTool.Initialize () [0x00000] in <filename unknown>:0 

  at TrafficManager.UI.TrafficManagerTool.Awake () [0x00000] in <filename unknown>:0 
UnityEngine.GameObject:Internal_AddComponentWithType(Type)
UnityEngine.GameObject:AddComponent(Type)
UnityEngine.GameObject:AddComponent()
TrafficManager.LoadingExtension:EnableTool()
TrafficManager.LoadingExtension:SetToolMode(TrafficManagerMode)
TrafficManager.UI.UIBase:Show()
TrafficManager.UI.UIBase:ButtonClick(UIComponent, UIMouseEventParameter)
ColossalFramework.UI.UIComponent:OnClick(UIMouseEventParameter)
ColossalFramework.UI.UIButton:OnClick(UIMouseEventParameter)
ColossalFramework.UI.MouseHandler:ProcessInput(IInputTranslator, Ray, UIComponent, Boolean)
ColossalFramework.UI.UIInput:ProcessMouseInput()
ColossalFramework.UI.UIInput:Update()

```

**Comment by VictorPhilipp** [comment] 2016-09-08 11:05
Thanks, the problem is known and will be fixed in the next version! As soon as I have the time, I will update the mod.

**Closed** 2016-09-08 11:06 UTC
Labels: bug

**Comment by Swamp-Ig** [comment] 2016-09-08 12:58
Awesome :)
