### ISSUE TITLE
Speed limits: Cannot set / save values

### ISSUE THREAD

**Issue by CRCinAU** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#44] opened 2016-12-26 11:17 UTC
v1.8.8:

Can't select the "Road type" in the default speed limits dialog. Can only see the "Dam" road type. Left and right arrows do nothing.

I also notice that the limits I set are not saved in the game. I usually make my highways 140 - and default them to that - but they're all currently 100.

**Comment by VictorPhilipp** [comment] 2016-12-31 16:14
I would strongly assume that this is caused by another mod. Could you please post your TMPE.log and output_log.txt in here right after you encountered this issue?

**Comment by CRCinAU** [comment] 2017-01-01 02:19
In other news, after the 1.8.9 update, the 'set defaults' button doesn't even bring up a window.... Before I go hunting, does it matter if this is on Linux instead of Windows?

**Comment by CRCinAU** [comment] 2017-01-01 02:22
[TMPE.log.txt](https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/files/679905/TMPE.log.txt)

Looks like one culprit:
```
[Info] @ 1380858 OnBeforeLoadData: SpeedLimitManager
[Error] @ 2291669 OnLoadData: Error while initializing SpeedLimitManager: System.NullReferenceException: Object reference not set to an instance of an object
  at TrafficManager.Manager.SpeedLimitManager.OnBeforeLoadData () [0x00000] in <filename unknown>:0 
  at TrafficManager.State.SerializableDataExtension.OnLoadData () [0x00000] in <filename unknown>:0 
   at TrafficManager.Log.LogToFile(System.String log, LogLevel level)
   at TrafficManager.Log.Error(System.String s)
   at TrafficManager.State.SerializableDataExtension.OnLoadData()
   at SerializableDataWrapper.OnLoadData()
   at SimulationManager.LateUpdateData(UpdateMode mode, Single minProgress, Single maxProgress)
   at SimulationManager.Managers_LateUpdateData(UpdateMode mode, Single minProgress, Single maxProgress)
   at LoadingManager+<LoadSimulationData>c__Iterator7B.MoveNext()
   at AsyncTask.Execute()
   at SimulationManager.SimulationStep()
   at SimulationManager.SimulationThread()
```

and maybe another:
```
[Info] @ 3273057 Loading State from Config
[Warning] @ 3276450 Priority segments data structure (old) undefined!
   at TrafficManager.Log.LogToFile(System.String log, LogLevel level)
   at TrafficManager.Log.Warning(System.String s)
   at TrafficManager.State.SerializableDataExtension.LoadDataState(Boolean ByRef error)
   at TrafficManager.State.SerializableDataExtension.DeserializeData(System.Byte[] data)
   at TrafficManager.State.SerializableDataExtension.OnLoadData()
   at SerializableDataWrapper.OnLoadData()
   at SimulationManager.LateUpdateData(UpdateMode mode, Single minProgress, Single maxProgress)
   at SimulationManager.Managers_LateUpdateData(UpdateMode mode, Single minProgress, Single maxProgress)
   at LoadingManager+<LoadSimulationData>c__Iterator7B.MoveNext()
   at AsyncTask.Execute()
   at SimulationManager.SimulationStep()
   at SimulationManager.SimulationThread()
```

in fact, there's a couple more like that too

Can't seem to find an output_log.txt present.

**Comment by VictorPhilipp** [comment] 2017-01-01 15:48
Many thanks for your logfile! It seems that one of your mods (maybe Network Extensions) adds an erroneous road type to the game but I am not 100% sure.

Although I have been unable to reproduce your issue (I enabled the exact same mods you are using) I have checked the relevant parts of TMPE and implemented additional checks. I would claim that the error should be fixed by now. Let me know if it still occurs for you.

In any case, I would be happy if you could send me your TMPE.log file again (after trying again, of course). I am interested in which condition caused the problem (I added some new debugging info that tells me what goes wrong).

**Comment by CRCinAU** [comment] 2017-01-02 00:14
I can confirm that 1.8.11 fixes the issues.

[TMPE.log.txt](https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/files/680282/TMPE.log.txt)

There's still a couple of warnings, but the speed limits were loaded correctly as soon as I loaded the game.

I guess the good part is:
[Info] @ 4615193 Loading lane speed limit data. 3393 elements

**Comment by VictorPhilipp** [comment] 2017-01-02 01:11
Yeah! Thanks for your time and for helping me fixing this issue! :-)

**Closed** 2017-01-02 01:11 UTC
Labels: enhancement, works for me
